@echo off
:: Gradle start up script for Windows
:: Generated by ChatGPT for repository: godofthunder7890-crypto/ChildMonitor
:: Resolve JAVA_HOME
if defined JAVA_HOME (
  set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
) else (
  set "JAVA_EXE=java"
)
:: Path to the wrapper JAR
set "EXEC_JAR=%~dp0gradle\wrapper\gradle-wrapper.jar"
:checkJar
if not exist "%EXEC_JAR%" (
  echo WARNING: gradle-wrapper.jar not found at %EXEC_JAR%
  echo This script will try to run 'gradle' from PATH instead.
  where gradle >nul 2>&1
  if %errorlevel%==0 (
    gradle %*
    exit /b %errorlevel%
  ) else (
    echo Could not find a Gradle installation. Either commit the gradle-wrapper.jar or install Gradle locally.
    exit /b 1
  )
)
:: Execute the wrapper
"%JAVA_EXE%" -jar "%EXEC_JAR%" org.gradle.wrapper.GradleWrapperMain %*
