#!/usr/bin/env sh
##############################################################################
# Gradle start up script for UN*X
#
# Generated by ChatGPT for repository: godofthunder7890-crypto/ChildMonitor
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx2048m"

APP_NAME="Gradle"
PROGNAME=$(basename "$0")

# Resolve links - $0 may be a softlink
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")"/"$link
  fi
done

PRGDIR=$(dirname "$PRG")
EXEC_JAR="$PRGDIR/gradle/wrapper/gradle-wrapper.jar"

CLASSPATH="$EXEC_JAR"

if [ -z "$JAVA_HOME" ]; then
  java="java"
else
  java="$JAVA_HOME/bin/java"
fi

if [ ! -f "$EXEC_JAR" ]; then
  echo "WARNING: Gradle wrapper jar not found at $EXEC_JAR"
  echo "This script will try to run 'gradle' from the PATH instead."
  if command -v gradle >/dev/null 2>&1; then
    exec gradle "$@"
  else
    echo "Could not find a Gradle installation. Either commit the gradle-wrapper.jar or install Gradle locally."
    exit 1
  fi
fi

exec "$java" $DEFAULT_JVM_OPTS -jar "$EXEC_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
